---
- hosts: webservers
  become: true

  tasks:
    - name: Create Application Network
      docker_network:
        name: app_network


    - name: Copy the files to new host
      copy:
        src: /var/lib/jenkins/workspace/8 - Run Python Scripts/application/html
        dest: /home/team3-iac/application/


    - name: Deploy PHP
      community.docker.docker_container:
        name: php
        image: php:7-fpm
        command: docker-php-ext-install mysqli
        networks:
          - name: app_network
        volumes:
          - /home/team3-iac/application/html:/var/www/html
        restart_policy: always


    - name: Sleep for 60 seconds and continue with play
      wait_for:
        timeout: 180
      delegate_to: localhost


    - name: Install mysqli extension on php
      community.docker.docker_container_exec:
        container: php
        command: /bin/bash -c "docker-php-ext-install mysqli"
        chdir: /


    - name: Deploy Web Application
      community.docker.docker_container:
        name: nginx
        image: nginx
        ports:
          - "80:80"
        networks:
          - name: app_network
        links:
          - php
        volumes:
          - /home/team3-iac/application/html:/var/www/html
          - /home/team3-iac/application/html/site.conf:/etc/nginx/conf.d/default.conf
        env:
          url: http://iac-team3.westeurope.cloudapp.azure.com:80
        restart_policy: always


    - name: Deploy Application Database
      community.docker.docker_container:
        name: mariadb
        image: mariadb:10.3
        ports:
          - "3306:3306"
        networks:
          - name: app_network
        volumes:
          - /home/team3-iac/application/mariadb:/var/lib/mysql
        env:
          MYSQL_ROOT_PASSWORD: example
          MYSQL_USER: app-user
          MYSQL_PASSWORD: example
        restart_policy: always


    - name: Deploy phpMyAdmin
      community.docker.docker_container:
        name: phpmyadmin
        image: phpmyadmin
        ports:
          - "8090:80"
        networks:
          - name: app_network
        links:
          - mariadb
        env:
          PMA_ARBITRARY: "1"
          PMA_HOST: "mariadb"
          PMA_PORT: "3306"
          PMA_USER: "root"
          PMA_PASSWORD: "example"
        restart_policy: always

